### ISSUE TITLE
Generate a session to prevent logging in every time

### ISSUE THREAD

**Issue by nextin-wu** [italoseara/whatsappy#5]
1.Can you generate a session to prevent logging in every time？
2.Can whatsapp add a number that is not in the address book into the group?

**Comment by italoseara** [comment]
1 - i already did it, but it still happens when you close the python console without closing the webbrowser, so, you should try to put `whatsapp.close()` in the end of the program to prevent this kinds of bugs (i'll try to solve this in the next update)

2 - Yes, but only with invite link, i'll create a function for that, meanwhile you can do it using the existing functions
